### PR TITLE
Fix compiling against libimobiledevice 1.2.0

### PR DESCRIPTION
**Pull request by simonbuchan**
Needed for iOS 8 support, AFAIK.

Tested against old work iPad 2 on 8.1.3

### CODE REVIEW

**Comment by simonbuchan** [comment]
This should fix https://bugs.launchpad.net/ubuntu/+source/libimobiledevice/+bug/1388743

**Comment by simonbuchan** [comment]
Example install output, showing extracted `operation`:

```
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/VideoTest.app/SC_Info/VideoTest.sinf in archive!
Copying 'VideoTest.ipa' to device... DONE.
Installing 'com.skilitics.interact.VideoTest'
Install - CreatingStagingDirectory (5%)
Install - ExtractingPackage (15%)
Install - InspectingPackage (20%)
Install - TakingInstallLock (20%)
Install - PreflightingApplication (30%)
Install - InstallingEmbeddedProfile (30%)
Install - VerifyingApplication (40%)
Install - CreatingContainer (50%)
Install - InstallingApplication (60%)
Install - PostflightingApplication (70%)
Install - SandboxingApplication (80%)
Install - GeneratingApplicationMap (90%)
Install - Complete
```

**Comment by simonbuchan** [comment]
Obsolete now :)

**Comment by FunkyM** [comment]
Yes, still thanks. :)

**Pull request closed without merging**
