### PR TITLE
Updates version to use CFBundleShortVersionString first instead.

### PR DESCRIPTION
**Pull request by trile127**

### CODE REVIEW

**Comment by trile127** [comment]
Please check ASAP!

**Comment by dcnt** [comment]
Please merge this update.
Thanks.

**Comment by dcnt** [comment]
> Ready

Thank you so much.

**Comment by trile127** [comment]
@dcnt The build.yml is looking for an artifact that doesnt exist!

**Comment by nikias** [comment]
This has been added with commit 14dced8ddab73ea51e42fe8da2180f259feae119.

**Pull request closed without merging**
